language: node_js
install:
    - yarn install --frozen-lockfile
script: CI=true yarn test:travis
after_success:
  - cat ./coverage/lcov.info|./node_modules/coveralls/bin/coveralls.js
node_js:
  - 10
addons:
    apt:
        packages:
            - xvfb
